Practica1b/P1-ejb/src/server/ssii2/visa/PagoBean.java
/**
 * Pr&aacute;ctricas de Sistemas Inform&aacute;ticos II
 * 
 * Esta clase incluye los datos necesarios para realizar un pago. En esta
 * primera versi&oacute; no se a&ntilde;ade aun el bean Tarjeta
 */

package ssii2.visa;

/**
 *
 * @author jaime
 */
public class PagoBean {
    
	private String idTransaccion; 
	private String idComercio;  
	private double importe;
        private String ruta_retorno;
        
        private TarjetaBean tarjeta;
        
        /* Calculados por el gestor de medios de pago */
        private String codRespuesta;    
        private String idAutorizacion;  

    /**
     * @return el ID de transacci&oacute;n
     */
    public String getIdTransaccion() {
        return idTransaccion;
    }

    /**
     * @param idTransaccion el ID de transacci&oacute;n
     */
    public void setIdTransaccion(String idTransaccion) {
        this.idTransaccion = idTransaccion;
    }

    /**
     * @return el ID del comercio
     */
    public String getIdComercio() {
        return idComercio;
    }

    /**
     * @param idComercio el ID del comercio
     */
    public void setIdComercio(String idComercio) {
        this.idComercio = idComercio;
    }

    /**
     * @return el importe
     */
    public double getImporte() {
        return importe;
    }

    /**          
     * @param importe el nuevo importe. Si hubiera alg&uacute;n error en la 
     * cadena de caracteres, el importe final se establecer&iacute;a a negativo. 
     */
    public void setImporte(String importe) {
        try {
            this.importe = Double.parseDouble(importe);            
        } catch (NumberFormatException e) {
            this.importe = -1;
        } catch (NullPointerException e) {
            this.importe = -1;      
        }
    }
    
    /**
     * @param importe el nuevo importe. 
     */
    public void setImporte(double importe) {
        this.importe = importe;
    }

    /**
     * @return la ruta de retorno
     */
    public String getRutaRetorno() {
        return this.ruta_retorno;
    }
    
    /**
     * @param ruta la ruta de retorno
     */
    public void setRutaRetorno(String ruta) {
        this.ruta_retorno = ruta;
    }

    /**
     * @return el c&oacute;digo de respuesta
     */
    public String getCodRespuesta() {
        return codRespuesta;
    }

    /**
     * @param codRespuesta c&oacute;digo de respuesta
     */
    public void setCodRespuesta(String codRespuesta) {
        this.codRespuesta = codRespuesta;
    }

    /**
     * @return el ID de autorizaci&oacute;n
     */
    public String getIdAutorizacion() {
        return idAutorizacion;
    }

    /**
     * @param idAutorizacion el ID de autorizaci&oacute;n
     */
    public void setIdAutorizacion(String idAutorizacion) {
        this.idAutorizacion = idAutorizacion;
    }
    
    /**
     * @return la tarjeta
     */
    public TarjetaBean getTarjeta() {
        return tarjeta;
    }

    /**
     * @param tarjeta bean tarjeta 
     */
    public void setTarjeta(TarjetaBean tarjeta) {
        this.tarjeta = tarjeta;
    }
}

Practica1b/P1-ejb/web/borradoerror.jsp
<%-- 
    Document   : Listado de pagos
    Created on : Feb 8, 2010, 12:33:44 PM
    Author     : phaya
--%>

<jsp:include page="cabecera.jsp"/>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

    <p>Error en el borrado de pagos para el comercio <%= request.getParameter("idComercio") %> </p>
    <p><a href="<c:url value='<%= request.getParameter("ruta") %>'/>">Volver al comercio</a></p>        

<%@ include file="pie.html" %>      

Practica1b/P1-ejb/web/borradook.jsp
<%-- 
    Document   : Listado de pagos
    Created on : Feb 8, 2010, 12:33:44 PM
    Author     : phaya
--%>

<jsp:include page="cabecera.jsp"/>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

    <p>Se han borrado <%= request.getAttribute("borrados") %> pagos correctamente para el comercio <%= request.getParameter("idComercio") %> </p>
    <p><a href="<c:url value='<%= request.getParameter("ruta") %>'/>">Volver al comercio</a></p>        

<%@ include file="pie.html" %>      

Practica1b/P1-ejb/web/cabecera.jsp
<%-- 
    Document   : index
    Created on : Jan 23, 2010, 7:35:48 PM
    Author     : phaya
--%>

<%@page contentType="text/html" pageEncoding="ISO-8859-1"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <title>Sistema de Pago con tarjeta</title>
        <style type="text/css">
            td.error {color:red;font-size:0.65em;}  
        </style>
    </head>
    <body>               
        <h1>Pago con tarjeta</h1>

Practica1b/P1-ejb/web/formdatosvisa.jsp
<%-- 
    Document   : ObtieneDatosVisa
    Created on : Jan 23, 2010, 7:47:05 PM
    Author     : phaya
--%>

<jsp:include page="cabecera.jsp"/>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<jsp:useBean id="pago" scope="session" class="ssii2.visa.PagoBean" />    
 
        <form action="procesapago" method="POST">   
            <table>
                <tr><td>Numero de visa: </td><td><input type="text" name="numero"  size="16" /></td></tr>                                              
                <c:if test="${not empty requestScope.ErrorVisaNumero}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaNumero.textoError}</td></tr>                  
                </c:if>                
                <tr><td>Titular: </td><td><input type="text" name="titular" size="25" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaTitular}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaTitular.textoError}</td></tr>                  
                </c:if>                
                <tr><td>Fecha Emisi&oacute;n:</td><td><input type="text" name="fechaEmision" maxlength="10" size="10" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaFechaEmision}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaFechaEmision.textoError}</td></tr>                  
                </c:if>                
                <tr><td>Fecha Caducidad: </td><td><input type="text" name="fechaCaducidad" maxlength="10" size="10" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaFechaCaducidad}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaFechaCaducidad.textoError}</td></tr>                  
                </c:if>
                <tr><td>CVV2:</td><td><input type="text" name="codigoVerificacion" maxlength="3" size="3" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaCVV}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaCVV.textoError}</td></tr>                  
                </c:if>
                <tr><td colspan="2"><input type="submit" value="Pagar" name="EnviarPago" /></td></tr>                
            </table>
            <hr/>
            <table>
                <tr><td>Id Transacci&oacute;n:</td><td>${pago.idTransaccion}</td></tr>
                <tr><td>Id Comercion:</td><td>${pago.idComercio}</td></tr>
                <tr><td>Importe:</td><td>${pago.importe}</td></tr>
            </table>
        </form>

<%@ include file="pie.html" %>

Practica1b/P1-ejb/web/listapagos.jsp
<%-- 
    Document   : Listado de pagos
    Created on : Feb 8, 2010, 12:33:44 PM
    Author     : phaya
--%>

<jsp:include page="cabecera.jsp"/>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<%-- Se obtiene la lista de pagos recibida de la request --%>
<jsp:useBean id="pagos" scope="request" class="ssii2.visa.PagoBean[]" />   

<%-- Se utiliza un bean para obtener los datos del pago e imprimirlos como
     comprobación      
     * idTransaccion;
     * idComercio;
     * importe;
     * codRespuesta
     * idAutorizacion 
     * ruta
--%>


        <p>Lista de pagos del comercio <%= request.getParameter("idComercio") %> </p>
        <table border="1">    
		<thead>
            <tr>
				<th>idTransaccion</th>
                <th>Importe</th>
                <th>codRespuesta</th>
				<th>idAutorizacion</th>
			</tr>
		</thead>
		<tbody>
			<c:forEach var="pago" items="${pagos}">
				<tr>
					<td>${pago.idTransaccion}</td>
					<td>${pago.importe}</td>
					<td>${pago.codRespuesta}</td>
					<td>${pago.idAutorizacion}</td>
				</tr>
			</c:forEach>
		</tbody>
		</table>
        
		<p><a href="<c:url value='<%= request.getParameter("ruta") %>'/>">Volver al comercio</a></p>        

<%@ include file="pie.html" %>      

Practica1b/P1-ejb/web/pagoexito.jsp
<%-- 
    Document   : OperacionExito
    Created on : Feb 8, 2010, 12:33:44 PM
    Author     : phaya
--%>

<jsp:include page="cabecera.jsp"/>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<%-- Se utiliza un bean para obtener los datos del pago e imprimirlos como
     comprobación      
     * idTransaccion;
     * idComercio;
     * importe;
     * codRespuesta
     * idAutorizacion 
     * ruta
--%>
<jsp:useBean id="pago" scope="request" class="ssii2.visa.PagoBean" />   

        <p>Pago realizado con &eacute;xito. A continuaci&oacute;n se muestra el 
        comprobante del mismo:</p> 
        <table>    
            <tr><td>idTransaccion:</td><td>${pago.idTransaccion}</td></tr>
            <tr><td>idComercio:</td><td>${pago.idComercio}</td></tr>
            <tr><td>importe:</td><td>${pago.importe}</td></tr>
            <tr><td>codRespuesta:</td><td>${pago.codRespuesta}</td></tr>
            <tr><td>idAutorizacion:</td><td>${pago.idAutorizacion}</td></tr>
        </table>
        <p><a href="<c:url value='${pago.rutaRetorno}'/>">Volver al comercio</a></p>        

<%@ include file="pie.html" %>      

Practica1b/P1-ejb/web/testbd.jsp
<%-- 
    Document   : ObtieneDatosVisa
    Created on : Jan 23, 2010, 7:47:05 PM
    Author     : phaya
--%>

<jsp:include page="cabecera.jsp"/>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

	<h2>Proceso de un pago</h2>
        <form action="procesapago" method="POST">   
            <table>
				<tr>
                    <td>Id Transacci&oacute;n: </td>
                    <td><input type="text" name="idTransaccion" maxlength="4" size="4" /></td>
                </tr>
                <tr>
                    <td>Id Comercio: </td>
                    <td><input type="text" name="idComercio" maxlength="4" size="4" /></td>
                </tr>
                <tr>
                    <td>Importe: </td>
                    <td><input type="text" name="importe" maxlength="4" size="4" /></td>
                </tr>                
                <tr><td>Numero de visa: </td><td><input type="text" name="numero"  size="16" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaNumero}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaNumero.textoError}</td></tr>                  
                </c:if>                
                <tr><td>Titular: </td><td><input type="text" name="titular" size="25" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaTitular}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaTitular.textoError}</td></tr>                  
                </c:if>                
                <tr><td>Fecha Emisi&oacute;n:</td><td><input type="text" name="fechaEmision" maxlength="10" size="10" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaFechaEmision}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaFechaEmision.textoError}</td></tr>                  
                </c:if>                
                <tr><td>Fecha Caducidad: </td><td><input type="text" name="fechaCaducidad" maxlength="10" size="10" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaFechaCaducidad}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaFechaCaducidad.textoError}</td></tr>                  
                </c:if>
                <tr><td>CVV2:</td><td><input type="text" name="codigoVerificacion" maxlength="3" size="3" /></td></tr>
                <c:if test="${not empty requestScope.ErrorVisaCVV}">                   
                  <tr><td colspan="2" class="error">${requestScope.ErrorVisaCVV.textoError}</td></tr>                  
                </c:if>
				<tr>
                    <td>Modo debug: </td>
                    <td><input type="radio" name="debug" value="true" /> True <input type="radio" name="debug" value="false" /> False</td>
                </tr>
				<tr>
                    <td>Direct Connection: </td>
                    <td><input type="radio" name="directConnection" value="true" /> True <input type="radio" name="directConnection" value="false" /> False</td>
                </tr>
				<tr>
                    <td>Use Prepared: </td>
                    <td><input type="radio" name="usePrepared" value="true" /> True <input type="radio" name="usePrepared" value="false" /> False</td>
                </tr>
                <tr><td colspan="2"><input type="submit" value="Pagar" name="EnviarPago" /></td></tr>                
            </table>
			<input type="hidden" name="ruta" value="/testbd.jsp" />			
            <hr/>            
        </form>
		
		<h2>Consulta de pagos</h2>
		<form action="getpagos" method="POST">  
			<table>
				<tr>
                    <td>Id Comercio: </td>
                    <td><input type="text" name="idComercio" maxlength="4" size="4" /></td>
                </tr>		
				<tr><td colspan="2"><input type="submit" value="GetPagos" name="Recuperar pagos" /></td></tr>                
            </table>
			
			<input type="hidden" name="ruta" value="/testbd.jsp" />
			<input type="hidden" name="debug" value="false" />
			<input type="hidden" name="directConnection" value="false" />
			<input type="hidden" name="usePrepared" value="true" />
            <hr/>            
        </form>
		
		<h2>Borrado de pagos</h2>	
		<form action="delpagos" method="POST">  
			<table>
				<tr>
                    <td>Id Comercio: </td>
                    <td><input type="text" name="idComercio" maxlength="4" size="4" /></td>
                </tr>		
				<tr><td colspan="2"><input type="submit" value="DelPagos" name="Borrar pagos" /></td></tr>                
            </table>
			
			<input type="hidden" name="ruta" value="/testbd.jsp" />
			<input type="hidden" name="debug" value="true" />
			<input type="hidden" name="directConnection" value="false" />
			<input type="hidden" name="usePrepared" value="true" />
            <hr/>            
        </form>

<%@ include file="pie.html" %>